title: My GitHub Homepage 
author: jtcuthbert
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Awesome description here for my new site, a place where I can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
twitter_username: @jcuthbert
github_username:  jtcuthbert

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
