title: John's Page  
author: jtcuthbert
email: johnsmail@johncuthbert.com
description: > # this means to ignore newlines until "baseurl:"
  My description

# social links
twitter_username: @jcuthbert
github_username:  jtcuthbert

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-slat
