My Github Coding Homebase
author: jtcuthbert
email: jc1458699@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my Github and coding homebase.

# social links
twitter_username: @jcuthbert
github_username:  jtcuthbert

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-slate
